class ContentsRepository {
  Map<String, dynamic> data = {
      "singa": [
          {
              "cid" : "1",
              "image": "assets/images/ara-1.jpg",
              "title": "네메시스 축구화275",
              "location": "제주 제주시 아라동",
              "price": "30000",
              "likes": "2",
          },
          {
              "cid" : "2",
              "image": "assets/images/ara-2.jpg",
              "title": "LA갈비 5Kg팔아요~",
              "location": "제주 제주시 아라동",
              "price": "10000",
              "likes": "6",
          },
          {
              "cid" : "3",
              "image": "assets/images/ara-4.jpg",
              "title": "[풀박스]맥북프로16인치 터치바 스페이스그레이",
              "location": "제주 제주시 아라동",
              "price": "2500000",
              "likes": "4",
          },
          {
              "cid" : "4",
              "image": "assets/images/ara-5.jpg",
              "title": "네메시스 축구화275",
              "location": "제주 제주시 아라동",
              "price": "30000",
              "likes": "10",
          },
          {
              "cid" : "5",
              "image": "assets/images/ara-6.jpg",
              "title": "갤럭시s10",
              "location": "제주 제주시 아라동",
              "price": "1890000",
              "likes": "2",
          },
          {
              "cid" : "6",
              "image": "assets/images/ara-7.jpg",
              "title": "선반",
              "location": "제주 제주시 아라동",
              "price": "14000",
              "likes": "1",
          },
          {
              "cid" : "7",
              "image": "assets/images/ara-8.jpg",
              "title": "냉장 쇼케이스",
              "location": "제주 제주시 아라동",
              "price": "60000",
              "likes": "4",
          },
          {
              "cid" : "8",
              "image": "assets/images/ara-9.jpg",
              "title": "대우미니냉장고",
              "location": "제주 제주시 아라동",
              "price": "30000",
              "likes": "7",
          },
          {
              "cid" : "9",
              "image": "assets/images/ara-10.jpg",
              "title": "멜킨스 풀업 운동기구",
              "location": "제주 제주시 아라동",
              "price": "56000",
              "likes": "9",
          },
      ],
      "unnam": [
          {
              "cid" : "10",
              "image": "assets/images/ora-1.jpg",
              "title": "네메시스 축구화275",
              "location": "제주 제주시 아라동",
              "price": "무료나눔",
              "likes": "2",
          },
          {
              "cid" : "11",
              "image": "assets/images/ora-2.jpg",
              "title": "LA갈비 5Kg팔아요~",
              "location": "제주 제주시 아라동",
              "price": "10000",
              "likes": "6",
          },
          {
              "cid" : "12",
              "image": "assets/images/ora-4.jpg",
              "title": "[풀박스]맥북프로16인치 터치바 스페이스그레이",
              "location": "제주 제주시 아라동",
              "price": "2500000",
              "likes": "4",
          },
          {
              "cid" : "13",
              "image": "assets/images/ora-5.jpg",
              "title": "네메시스 축구화275",
              "location": "제주 제주시 아라동",
              "price": "30000",
              "likes": "10",
          },
          {
              "cid" : "14",
              "image": "assets/images/ora-6.jpg",
              "title": "갤럭시s10",
              "location": "제주 제주시 아라동",
              "price": "1890000",
              "likes": "2",
          },
          {
              "cid" : "15",
              "image": "assets/images/ora-7.jpg",
              "title": "선반",
              "location": "제주 제주시 아라동",
              "price": "14000",
              "likes": "1",
          },
          {
              "cid" : "16",
              "image": "assets/images/ora-8.jpg",
              "title": "냉장 쇼케이스",
              "location": "제주 제주시 아라동",
              "price": "60000",
              "likes": "4",
          },
          {
              "cid" : "17",
              "image": "assets/images/ora-9.jpg",
              "title": "대우미니냉장고",
              "location": "제주 제주시 아라동",
              "price": "30000",
              "likes": "7",
          },
          {
              "cid" : "18",
              "image": "assets/images/ora-10.jpg",
              "title": "멜킨스 풀업 운동기구",
              "location": "제주 제주시 아라동",
              "price": "56000",
              "likes": "9",
          },
      ],
      "sinchang": [
          {
              "cid" : "19",
              "image": "assets/images/ara-1.jpg",
              "title": "네메시스 축구화275",
              "location": "제주 제주시 아라동",
              "price": "30000",
              "likes": "2",
          },
          {
              "cid" : "20",
              "image": "assets/images/ara-2.jpg",
              "title": "LA갈비 5Kg팔아요~",
              "location": "제주 제주시 아라동",
              "price": "10000",
              "likes": "6",
          },
          {
              "cid" : "21",
              "image": "assets/images/ara-4.jpg",
              "title": "[풀박스]맥북프로16인치 터치바 스페이스그레이",
              "location": "제주 제주시 아라동",
              "price": "2500000",
              "likes": "4",
          },
          {
              "cid" : "22",
              "image": "assets/images/ara-5.jpg",
              "title": "네메시스 축구화275",
              "location": "제주 제주시 아라동",
              "price": "30000",
              "likes": "10",
          },
          {
              "cid" : "23",
              "image": "assets/images/ara-6.jpg",
              "title": "갤럭시s10",
              "location": "제주 제주시 아라동",
              "price": "1890000",
              "likes": "2",
          },
          {
              "cid" : "24",
              "image": "assets/images/ara-7.jpg",
              "title": "선반",
              "location": "제주 제주시 아라동",
              "price": "14000",
              "likes": "1",
          },
          {
              "cid" : "25",
              "image": "assets/images/ara-8.jpg",
              "title": "냉장 쇼케이스",
              "location": "제주 제주시 아라동",
              "price": "60000",
              "likes": "4",
          },
          {
              "cid" : "26",
              "image": "assets/images/ara-9.jpg",
              "title": "대우미니냉장고",
              "location": "제주 제주시 아라동",
              "price": "30000",
              "likes": "7",
          },
          {
              "cid" : "27",
              "image": "assets/images/ara-10.jpg",
              "title": "멜킨스 풀업 운동기구",
              "location": "제주 제주시 아라동",
              "price": "56000",
              "likes": "9",
          },
      ],
  };
  Future<List<Map<String,String>>> loadContentsFromLocation(
      String location) async{
      await Future.delayed(Duration(milliseconds: 1000));
      return data[location];
  }
}